package main

import (
	"bufio"
	"encoding/json"
	"fmt"
	"os"
	"strconv"
	"strings"
	"time"

	"aws-tag-analyzer/internal/ai"
	"aws-tag-analyzer/internal/aws"
	"aws-tag-analyzer/internal/config"
	"aws-tag-analyzer/internal/policy"
	"aws-tag-analyzer/internal/recommendation"

	"github.com/rs/zerolog"
	"github.com/rs/zerolog/log"
	"github.com/spf13/cobra"
)

// ResourceInfo defines the structure for JSON output
type ResourceInfo struct {
	Kind   string                   `json:"kind"`
	Name   string                   `json:"name"`
	Region string                   `json:"region"`
	Tags   map[string]string        `json:"tags"`
	Issues []policy.ValidationIssue `json:"issues,omitempty"`
}

// Helper function to convert tags map to lowercase
func lowercaseTags(tags map[string]string) map[string]string {
	lowerTags := make(map[string]string, len(tags))
	for k, v := range tags {
		lowerTags[strings.ToLower(k)] = strings.ToLower(v)
	}
	return lowerTags
}

// Application version
var version = "0.1.0"

// Global variables to hold flag values (populated by Cobra)
var (
	logLevel   string
	cfg        *config.Config
	region     string
	lowercase  bool
	policyFile string
	aiModel    string
	aiTimeout  time.Duration
	inputJson  string
	inputFile  string
	applyKinds string
)

// rootCmd represents the base command when called without any subcommands
var rootCmd = &cobra.Command{
	Use:   "aws-tag-analyzer",
	Short: "AWS Resource Lister and Tag Analyzer",
	Long: `A tool to list AWS resources, validate their tags against a policy,
and optionally get AI-powered recommendations for fixing tag issues.
It can also apply these recommendations interactively.`,
	PersistentPreRunE: func(cmd *cobra.Command, args []string) error {
		// Configure zerolog for console output to stderr
		log.Logger = log.Output(zerolog.ConsoleWriter{Out: os.Stderr})
		// Set global log level based on the flag
		level, err := zerolog.ParseLevel(logLevel)
		if err != nil {
			log.Warn().Str("level", logLevel).Msg("Invalid log level specified, defaulting to 'info'")
			level = zerolog.InfoLevel
		}
		zerolog.SetGlobalLevel(level)
		log.Info().Str("level", level.String()).Msg("Log level set")

		// Load base configuration if not the version command
		if cmd.Name() != "version" {
			cfg, err = config.LoadConfig()
			if err != nil {
				log.Warn().Err(err).Msg("Failed to load .env file. Relying on environment variables or IAM role.")
				cfg = &config.Config{
					AWSRegion:          config.GetEnv("AWS_REGION", ""),
					AWSAccessKeyID:     config.GetEnv("AWS_ACCESS_KEY_ID", ""),
					AWSSecretAccessKey: config.GetEnv("AWS_SECRET_ACCESS_KEY", ""),
					AIAPIURL:           config.GetEnv("AI_API_URL", ""),
					AIAPIToken:         config.GetEnv("AI_API_TOKEN", ""),
				}
			}
		}
		return nil
	},
}

// analyzeCmd represents the analyze command
var analyzeCmd = &cobra.Command{
	Use:   "analyze",
	Short: "Analyze AWS resources for tag policy compliance and get recommendations",
	Long: `Fetches AWS resources (EC2, S3, etc.), validates their tags against a
specified policy file, and optionally uses an AI model to suggest fixes for
non-compliant tags. Outputs results as JSON. Can also read resource data from
a JSON file instead of fetching from AWS.`,
	Run: func(cmd *cobra.Command, args []string) {
		runAnalyzeCommand()
	},
}

// applyCmd represents the apply command
var applyCmd = &cobra.Command{
	Use:   "apply",
	Short: "Interactively apply tag recommendations from an analysis JSON file",
	Long: `Reads a JSON file generated by the 'analyze' command and interactively
prompts the user to apply the recommended tag changes to the corresponding
AWS resources.`,
	Run: func(cmd *cobra.Command, args []string) {
		if inputFile == "" {
			log.Fatal().Msg("-input flag is required for the apply command")
		}
		runApplyCommand()
	},
}

// versionCmd represents the version command
var versionCmd = &cobra.Command{
	Use:   "version",
	Short: "Print the version number",
	Run: func(cmd *cobra.Command, args []string) {
		runVersionCommand()
	},
}

// Execute adds all child commands to the root command and sets flags appropriately.
func Execute() {
	err := rootCmd.Execute()
	if err != nil {
		os.Exit(1)
	}
}

func init() {
	// Add global persistent flags (available to all commands)
	rootCmd.PersistentFlags().StringVar(&logLevel, "log-level", "info", "Set log level (trace, debug, info, warn, error, fatal, panic)")

	// Add subcommands to root command
	rootCmd.AddCommand(analyzeCmd)
	rootCmd.AddCommand(applyCmd)
	rootCmd.AddCommand(versionCmd)

	// --- analyzeCmd Flags ---
	analyzeCmd.Flags().StringVarP(&region, "region", "r", "", "Comma-separated list of AWS regions (overrides env/config)")
	analyzeCmd.Flags().BoolVarP(&lowercase, "lowercase", "l", false, "Convert output strings (kind, name, region, tags) to lowercase")
	analyzeCmd.Flags().StringVarP(&policyFile, "policy", "p", "", "Path to the tag policy JSON file (required)")
	analyzeCmd.Flags().StringVar(&aiModel, "ai-model", "", "Enable AI recommendations using the specified model name (e.g., 'gpt-4')")
	analyzeCmd.Flags().DurationVar(&aiTimeout, "ai-timeout", 20*time.Second, "Timeout duration for AI API requests")
	analyzeCmd.Flags().StringVar(&inputJson, "input-json", "", "Path to JSON file with pre-fetched resources (skips AWS fetch)")

	// --- applyCmd Flags ---
	applyCmd.Flags().StringVarP(&inputFile, "input", "i", "", "Path to the JSON file with resources and recommendations (required)")
	applyCmd.Flags().StringVarP(&applyKinds, "kind", "k", "", "Comma-separated list of resource kinds to apply changes to (e.g., ec2,s3)")
}

func main() {
	Execute()
}

// runAnalyzeCommand now uses global variables populated by Cobra.
func runAnalyzeCommand() {
	log.Info().Msg("Running analyze command...")

	// Determine if AI recommendations are enabled based on aiModel flag
	aiRecommendationsEnabled := aiModel != ""

	// Validate AI config if enabled
	if aiRecommendationsEnabled {
		if cfg.AIAPIURL == "" {
			log.Fatal().Msg("AI recommendations enabled via --ai-model, but AI_API_URL environment variable is not set.")
		}
		if cfg.AIAPIToken == "" {
			log.Fatal().Msg("AI recommendations enabled via --ai-model, but AI_API_TOKEN environment variable is not set.")
		}
		log.Info().Str("url", cfg.AIAPIURL).Str("model", aiModel).Msg("AI Recommendations enabled")
	} else {
		log.Info().Msg("AI Recommendations disabled (no model specified via --ai-model)")
	}

	// Load Tag Policy
	tagPolicy, err := policy.LoadPolicy(policyFile)
	if err != nil {
		log.Fatal().Err(err).Msg("Failed to load tag policy")
	}

	// Slice to hold all resource information
	var allResources []ResourceInfo

	// --- Check if reading from input JSON or fetching from AWS ---
	if inputJson != "" {
		log.Info().Str("file", inputJson).Msg("Reading resource data from input JSON file, skipping AWS fetch.")
		jsonData, err := os.ReadFile(inputJson)
		if err != nil {
			log.Fatal().Err(err).Str("file", inputJson).Msg("Failed to read input JSON file")
		}

		err = json.Unmarshal(jsonData, &allResources)
		if err != nil {
			log.Fatal().Err(err).Str("file", inputJson).Msg("Failed to unmarshal JSON data from input file")
		}
		log.Info().Int("count", len(allResources)).Str("file", inputJson).Msg("Successfully loaded resources from JSON file")

	} else {
		log.Info().Msg("Fetching resource data from AWS.")
		// --- Fetch from AWS ---

		// Determine target regions (only needed if fetching from AWS)
		var targetRegions []string
		if region != "" {
			targetRegions = strings.Split(region, ",")
			log.Info().Strs("regions", targetRegions).Msg("Using regions from --region flag")
		} else if cfg.AWSRegion != "" {
			targetRegions = []string{cfg.AWSRegion}
			log.Info().Str("region", cfg.AWSRegion).Msg("Using region from environment/config")
		} else {
			log.Fatal().Msg("AWS region must be set via --region flag, AWS_REGION environment variable, or in .env file when not using --input-json.")
		}

		// --- Resource Fetching Loops ---
		for _, currentRegion := range targetRegions {
			currentRegion = strings.TrimSpace(currentRegion)
			if currentRegion == "" {
				continue
			}

			log.Info().Str("region", currentRegion).Msg("Processing region")

			// Initialize AWS client for the current region
			client, err := aws.NewAWSClient(currentRegion)
			if err != nil {
				log.Error().Err(err).Str("region", currentRegion).Msg("Failed to create AWS client for region. Skipping.")
				continue
			}

			// --- EC2 Instances ---
			log.Info().Str("region", currentRegion).Msg("Fetching EC2 Instances...")
			instances, err := client.ListEC2Instances()
			if err != nil {
				log.Error().Err(err).Str("region", currentRegion).Msg("Failed to list EC2 instances")
			} else {
				log.Info().Int("count", len(instances)).Str("region", currentRegion).Msg("Fetched EC2 Instances")
				for _, instance := range instances {
					if instance != nil && instance.InstanceId != nil {
						tags := aws.ConvertEC2Tags(instance.Tags)
						kind := "ec2"
						name := *instance.InstanceId
						region := currentRegion
						if lowercase {
							kind = strings.ToLower(kind)
							name = strings.ToLower(name)
							region = strings.ToLower(region)
							tags = lowercaseTags(tags)
						}
						issues := policy.ValidateResource(kind, name, region, tags, tagPolicy, lowercase)
						resInfo := ResourceInfo{
							Kind:   kind,
							Name:   name,
							Region: region,
							Tags:   tags,
							Issues: issues,
						}
						allResources = append(allResources, resInfo)
					}
				}
			}

			// --- EBS Volumes ---
			log.Info().Str("region", currentRegion).Msg("Fetching EBS Volumes...")
			volumes, err := client.ListVolumes()
			if err != nil {
				log.Error().Err(err).Str("region", currentRegion).Msg("Failed to list volumes")
			} else {
				log.Info().Int("count", len(volumes)).Str("region", currentRegion).Msg("Fetched EBS Volumes")
				for _, volume := range volumes {
					if volume != nil && volume.VolumeId != nil {
						tags := aws.ConvertEC2Tags(volume.Tags)
						kind := "ebs"
						name := *volume.VolumeId
						region := currentRegion
						if lowercase {
							kind = strings.ToLower(kind)
							name = strings.ToLower(name)
							region = strings.ToLower(region)
							tags = lowercaseTags(tags)
						}
						issues := policy.ValidateResource(kind, name, region, tags, tagPolicy, lowercase)
						resInfo := ResourceInfo{
							Kind:   kind,
							Name:   name,
							Region: region,
							Tags:   tags,
							Issues: issues,
						}
						allResources = append(allResources, resInfo)
					}
				}
			}

			// --- VPCs ---
			log.Info().Str("region", currentRegion).Msg("Fetching VPCs...")
			vpcs, err := client.ListVPCs()
			if err != nil {
				log.Error().Err(err).Str("region", currentRegion).Msg("Failed to list VPCs")
			} else {
				log.Info().Int("count", len(vpcs)).Str("region", currentRegion).Msg("Fetched VPCs")
				for _, vpc := range vpcs {
					if vpc != nil && vpc.VpcId != nil {
						tags := aws.ConvertEC2Tags(vpc.Tags)
						kind := "vpc"
						name := *vpc.VpcId
						region := currentRegion
						if lowercase {
							kind = strings.ToLower(kind)
							name = strings.ToLower(name)
							region = strings.ToLower(region)
							tags = lowercaseTags(tags)
						}
						issues := policy.ValidateResource(kind, name, region, tags, tagPolicy, lowercase)
						resInfo := ResourceInfo{
							Kind:   kind,
							Name:   name,
							Region: region,
							Tags:   tags,
							Issues: issues,
						}
						allResources = append(allResources, resInfo)
					}
				}
			}

			// --- NAT Gateways ---
			log.Info().Str("region", currentRegion).Msg("Fetching NAT Gateways...")
			natGateways, err := client.ListNatGateways()
			if err != nil {
				log.Error().Err(err).Str("region", currentRegion).Msg("Failed to list NAT Gateways")
			} else {
				log.Info().Int("count", len(natGateways)).Str("region", currentRegion).Msg("Fetched NAT Gateways")
				for _, ngw := range natGateways {
					if ngw != nil && ngw.NatGatewayId != nil {
						tags := aws.ConvertEC2Tags(ngw.Tags)
						kind := "natgateway"
						name := *ngw.NatGatewayId
						region := currentRegion
						if lowercase {
							kind = strings.ToLower(kind)
							name = strings.ToLower(name)
							region = strings.ToLower(region)
							tags = lowercaseTags(tags)
						}
						issues := policy.ValidateResource(kind, name, region, tags, tagPolicy, lowercase)
						resInfo := ResourceInfo{
							Kind:   kind,
							Name:   name,
							Region: region,
							Tags:   tags,
							Issues: issues,
						}
						allResources = append(allResources, resInfo)
					}
				}
			}

			// --- Internet Gateways ---
			log.Info().Str("region", currentRegion).Msg("Fetching Internet Gateways...")
			internetGateways, err := client.ListInternetGateways()
			if err != nil {
				log.Error().Err(err).Str("region", currentRegion).Msg("Failed to list Internet Gateways")
			} else {
				log.Info().Int("count", len(internetGateways)).Str("region", currentRegion).Msg("Fetched Internet Gateways")
				for _, igw := range internetGateways {
					if igw != nil && igw.InternetGatewayId != nil {
						tags := aws.ConvertEC2Tags(igw.Tags)
						kind := "internetgateway"
						name := *igw.InternetGatewayId
						region := currentRegion
						if lowercase {
							kind = strings.ToLower(kind)
							name = strings.ToLower(name)
							region = strings.ToLower(region)
							tags = lowercaseTags(tags)
						}
						issues := policy.ValidateResource(kind, name, region, tags, tagPolicy, lowercase)
						resInfo := ResourceInfo{
							Kind:   kind,
							Name:   name,
							Region: region,
							Tags:   tags,
							Issues: issues,
						}
						allResources = append(allResources, resInfo)
					}
				}
			}

			// --- Elastic IPs ---
			log.Info().Str("region", currentRegion).Msg("Fetching Elastic IPs...")
			elasticIPs, err := client.ListElasticIPs()
			if err != nil {
				log.Error().Err(err).Str("region", currentRegion).Msg("Failed to list Elastic IPs")
			} else {
				log.Info().Int("count", len(elasticIPs)).Str("region", currentRegion).Msg("Fetched Elastic IPs")
				for _, ip := range elasticIPs {
					if ip != nil && ip.AllocationId != nil {
						tags := aws.ConvertEC2Tags(ip.Tags)
						kind := "eip"
						name := *ip.AllocationId
						region := currentRegion
						if lowercase {
							kind = strings.ToLower(kind)
							name = strings.ToLower(name)
							region = strings.ToLower(region)
							tags = lowercaseTags(tags)
						}
						issues := policy.ValidateResource(kind, name, region, tags, tagPolicy, lowercase)
						resInfo := ResourceInfo{
							Kind:   kind,
							Name:   name,
							Region: region,
							Tags:   tags,
							Issues: issues,
						}
						allResources = append(allResources, resInfo)
					}
				}
			}

			// --- Load Balancers (ELBv2) ---
			log.Info().Str("region", currentRegion).Msg("Fetching Load Balancers (v2)...")
			loadBalancers, err := client.ListLoadBalancers()
			if err != nil {
				log.Error().Err(err).Str("region", currentRegion).Msg("Failed to list load balancers")
			} else {
				log.Info().Int("count", len(loadBalancers)).Str("region", currentRegion).Msg("Fetched Load Balancers (v2)")
				for _, lb := range loadBalancers {
					if lb != nil && lb.LoadBalancerArn != nil {
						elbTags, err := client.GetLoadBalancerTags(lb.LoadBalancerArn)
						tags := aws.ConvertELBTags(elbTags)
						if err != nil {
							log.Warn().Str("arn", *lb.LoadBalancerArn).Str("region", currentRegion).Msg("Using empty tags for LB due to previous error")
							tags = make(map[string]string)
						}
						kind := "elbv2"
						name := *lb.LoadBalancerArn
						region := currentRegion
						if lowercase {
							kind = strings.ToLower(kind)
							name = strings.ToLower(name)
							region = strings.ToLower(region)
							tags = lowercaseTags(tags)
						}
						issues := policy.ValidateResource(kind, name, region, tags, tagPolicy, lowercase)
						resInfo := ResourceInfo{
							Kind:   kind,
							Name:   name,
							Region: region,
							Tags:   tags,
							Issues: issues,
						}
						allResources = append(allResources, resInfo)
					}
				}
			}

			// --- ECS Clusters ---
			log.Info().Str("region", currentRegion).Msg("Fetching ECS Clusters...")
			ecsClusters, err := client.ListECSClusters()
			if err != nil {
				log.Error().Err(err).Str("region", currentRegion).Msg("Failed to list ECS Clusters")
			} else {
				log.Info().Int("count", len(ecsClusters)).Str("region", currentRegion).Msg("Fetched ECS Clusters")
				for _, cluster := range ecsClusters {
					if cluster != nil && cluster.ClusterArn != nil {
						tags := aws.ConvertECSTags(cluster.Tags)
						kind := "ecscluster"
						name := *cluster.ClusterArn
						region := currentRegion
						if lowercase {
							kind = strings.ToLower(kind)
							name = strings.ToLower(name)
							region = strings.ToLower(region)
							tags = lowercaseTags(tags)
						}
						issues := policy.ValidateResource(kind, name, region, tags, tagPolicy, lowercase)
						resInfo := ResourceInfo{
							Kind:   kind,
							Name:   name,
							Region: region,
							Tags:   tags,
							Issues: issues,
						}
						allResources = append(allResources, resInfo)
					}
				}
			}

		} // --- End of region loop ---

		// --- S3 Buckets ---
		log.Info().Msg("Fetching S3 Buckets (Global List)...")
		primaryRegion := targetRegions[0]
		for _, r := range targetRegions {
			if strings.TrimSpace(r) != "" {
				primaryRegion = strings.TrimSpace(r)
				break
			}
		}

		s3Client, err := aws.NewAWSClient(primaryRegion)
		if err != nil {
			log.Error().Err(err).Str("region", primaryRegion).Msg("Failed to create AWS client for primary region S3 listing. Skipping S3.")
		} else {
			bucketInfos, err := s3Client.ListS3Buckets()
			if err != nil {
				log.Error().Err(err).Msg("Failed to list S3 buckets")
			} else {
				log.Info().Int("count", len(bucketInfos)).Msg("Fetched S3 Bucket list. Now fetching tags...")
				for _, bucketInfo := range bucketInfos {
					if bucketInfo.Name != nil {
						tags, err := s3Client.GetS3BucketTags(bucketInfo.Name, bucketInfo.Region)
						if err != nil {
							log.Warn().Str("bucket", *bucketInfo.Name).Str("region", bucketInfo.Region).Msg("Using empty tags for bucket due to previous error")
							tags = make(map[string]string)
						}
						kind := "s3"
						name := *bucketInfo.Name
						region := bucketInfo.Region
						if lowercase {
							kind = strings.ToLower(kind)
							name = strings.ToLower(name)
							region = strings.ToLower(region)
							tags = lowercaseTags(tags)
						}
						issues := policy.ValidateResource(kind, name, region, tags, tagPolicy, lowercase)
						resInfo := ResourceInfo{
							Kind:   kind,
							Name:   name,
							Region: region,
							Tags:   tags,
							Issues: issues,
						}
						allResources = append(allResources, resInfo)
					}
				}
				log.Info().Msg("Finished fetching S3 tags.")
			}
		}
		// --- End S3 Buckets ---
		// --- End Fetch from AWS ---
	}

	// --- Prepare Good Examples for AI ---
	var goodExamples []ai.ResourceExample
	const maxExamples = 3
	if aiRecommendationsEnabled {
		log.Debug().Msg("Searching for well-tagged resource examples...")
		count := 0
		for _, res := range allResources {
			if len(res.Issues) == 0 && count < maxExamples {
				goodExamples = append(goodExamples, ai.ResourceExample{
					Kind:   res.Kind,
					Name:   res.Name,
					Region: res.Region,
					Tags:   res.Tags,
				})
				count++
				log.Trace().Str("kind", res.Kind).Str("name", res.Name).Msg("Found good example resource")
			}
			if count >= maxExamples {
				break
			}
		}
		log.Debug().Int("count", len(goodExamples)).Msg("Collected well-tagged examples for AI context")
	}
	// --- End Prepare Good Examples ---

	// --- Process AI Recommendations (if enabled) ---
	if aiRecommendationsEnabled {
		log.Info().Dur("timeout", aiTimeout).Msg("Fetching AI recommendations sequentially for resources with issues...")
		totalIssues := 0
		processedIssues := 0
		for i := range allResources {
			res := &allResources[i]
			if len(res.Issues) > 0 {
				log.Info().Str("kind", res.Kind).Str("name", res.Name).Int("issue_count", len(res.Issues)).Msg("Processing issues for resource")
				for j := range res.Issues {
					issue := &res.Issues[j]
					totalIssues++

					log.Debug().
						Str("kind", res.Kind).
						Str("name", res.Name).
						Str("issue_type", issue.IssueType).
						Str("tag_key", issue.TagKey).
						Msg("Querying AI for recommendation")

					recommendationStr, err := ai.GetAIRecommendation(
						cfg.AIAPIURL,
						cfg.AIAPIToken,
						aiModel,
						res.Kind,
						res.Name,
						res.Region,
						res.Tags,
						*issue,
						goodExamples,
						aiTimeout,
					)

					processedIssues++
					if err != nil {
						log.Warn().Err(err).
							Str("kind", res.Kind).
							Str("name", res.Name).
							Str("issue_type", issue.IssueType).
							Str("tag_key", issue.TagKey).
							Msg("Failed to get AI recommendation")
					} else {
						log.Debug().
							Str("kind", res.Kind).
							Str("name", res.Name).
							Str("issue_type", issue.IssueType).
							Str("tag_key", issue.TagKey).
							Str("recommendation", recommendationStr).
							Str("model", aiModel).
							Msg("Received AI recommendation")
						issue.Recommendation = map[string]string{
							aiModel: recommendationStr,
						}
					}
				}
			}
		}
		log.Info().Int("processed_issues", processedIssues).Int("total_issues", totalIssues).Msg("Finished fetching AI recommendations.")
	}
	// --- End AI Processing ---

	log.Info().Msg("Marshalling results to JSON...")
	jsonData, err := json.MarshalIndent(allResources, "", "  ")
	if err != nil {
		log.Fatal().Err(err).Msg("Failed to marshal resources to JSON")
	}

	fmt.Println(string(jsonData))

	log.Info().Int("totalResources", len(allResources)).Msg("Processing complete.")
}

// runApplyCommand now uses global variables populated by Cobra.
func runApplyCommand() {
	log.Info().Str("file", inputFile).Msg("Running apply command...")

	// Process kind flag
	allowedKinds := make(map[string]bool)
	filterByKind := false
	if applyKinds != "" {
		filterByKind = true
		kinds := strings.Split(applyKinds, ",")
		for _, k := range kinds {
			trimmedKind := strings.TrimSpace(k)
			if trimmedKind != "" {
				allowedKinds[trimmedKind] = true
				log.Info().Str("kind", trimmedKind).Msg("Filtering for resource kind")
			}
		}
		if len(allowedKinds) == 0 {
			log.Warn().Str("flagValue", applyKinds).Msg("Kind filter flag was provided but contained no valid kinds after splitting and trimming.")
			filterByKind = false
		}
	}

	// Read the input JSON file
	jsonData, err := os.ReadFile(inputFile)
	if err != nil {
		log.Fatal().Err(err).Str("file", inputFile).Msg("Failed to read input JSON file")
	}

	// Unmarshal the JSON data
	var allResources []ResourceInfo
	err = json.Unmarshal(jsonData, &allResources)
	if err != nil {
		log.Fatal().Err(err).Str("file", inputFile).Msg("Failed to unmarshal JSON data from input file")
	}
	log.Info().Int("count", len(allResources)).Msg("Successfully loaded resources for application")

	reader := bufio.NewReader(os.Stdin)

	appliedCount := 0
	skippedCount := 0
	errorCount := 0

	// Iterate through resources and issues
	for _, resource := range allResources {
		// --- Filter by Kind ---
		if filterByKind {
			if _, ok := allowedKinds[resource.Kind]; !ok {
				log.Trace().Str("kind", resource.Kind).Str("name", resource.Name).Msg("Skipping resource due to kind filter")
				continue
			}
		}
		// --- End Filter by Kind ---

		if len(resource.Issues) == 0 {
			continue
		}

		for _, issue := range resource.Issues {
			if issue.Recommendation == nil || len(issue.Recommendation) == 0 {
				continue
			}

			// --- Display Common Resource Info ---
			fmt.Printf("Resource: %s %s (%s)\n", resource.Kind, resource.Name, resource.Region)
			if nameTag, ok := resource.Tags["Name"]; ok {
				fmt.Printf("  Name Tag: '%s'\n", nameTag)
			} else if nameTag, ok := resource.Tags["name"]; ok {
				fmt.Printf("  Name Tag: '%s'\n", nameTag)
			}
			fmt.Println("  Existing Tags:")
			if len(resource.Tags) > 0 {
				for k, v := range resource.Tags {
					fmt.Printf("    %s: %s\n", k, v)
				}
			} else {
				fmt.Println("    (No tags found)")
			}
			fmt.Printf("  Issue: %s (%s)\n", issue.IssueType, issue.TagKey)

			// --- Handle Single vs Multiple Recommendations ---
			if len(issue.Recommendation) == 1 {
				// --- Single Recommendation Logic ---
				var model, recString string
				for m, r := range issue.Recommendation {
					model, recString = m, r
					break
				}

				log.Debug().Str("kind", resource.Kind).Str("name", resource.Name).Str("model", model).Str("rec", recString).Msg("Processing single recommendation")

				action, key, value, err := recommendation.ParseRecommendation(recString)
				if err != nil {
					log.Error().Err(err).Str("recommendation", recString).Msg("Failed to parse recommendation, skipping")
					errorCount++
					continue
				}

				currentValue, exists := resource.Tags[key]
				if exists {
					fmt.Printf("  Current value for tag '%s': '%s'\n", key, currentValue)
				} else {
					fmt.Printf("  Tag '%s' is currently missing.\n", key)
				}
				fmt.Printf("  Recommendation (%s): %s tag '%s' with value '%s'\n", model, action, key, value)
				fmt.Print("Apply this change? (y/N/e[dit]): ")

				inputText, _ := reader.ReadString('\n')
				inputText = strings.TrimSpace(strings.ToLower(inputText))

				applyChange := false
				editedValue := value

				switch inputText {
				case "y":
					applyChange = true
					log.Info().Str("action", action).Str("key", key).Str("value", value).Str("kind", resource.Kind).Str("name", resource.Name).Msg("User approved applying change")
				case "e":
					fmt.Printf("Enter new value for tag '%s': ", key)
					newValueText, _ := reader.ReadString('\n')
					editedValue = strings.TrimSpace(newValueText)
					applyChange = true
					log.Info().Str("action", action).Str("key", key).Str("originalValue", value).Str("newValue", editedValue).Str("kind", resource.Kind).Str("name", resource.Name).Msg("User approved applying edited change")
				default:
					log.Warn().Str("action", action).Str("key", key).Str("value", value).Str("kind", resource.Kind).Str("name", resource.Name).Msg("User skipped applying change")
					skippedCount++
				}

				if applyChange {
					err := applyTagChange(cfg, resource, action, key, editedValue)
					if err != nil {
						log.Error().Err(err).Msg("Failed to apply tag change")
						errorCount++
					} else {
						log.Info().Msg("Successfully applied tag change")
						appliedCount++
					}
				}
				fmt.Println("---")

			} else {
				// --- Multiple Recommendations Logic ---
				log.Debug().Str("kind", resource.Kind).Str("name", resource.Name).Int("count", len(issue.Recommendation)).Msg("Processing multiple recommendations")

				var targetKey string
				var firstRecParsed bool
				for _, rec := range issue.Recommendation {
					_, k, _, err := recommendation.ParseRecommendation(rec)
					if err == nil {
						targetKey = k
						firstRecParsed = true
						break
					}
				}
				if firstRecParsed {
					currentValue, exists := resource.Tags[targetKey]
					if exists {
						fmt.Printf("  Current value for tag '%s': '%s'\n", targetKey, currentValue)
					} else {
						fmt.Printf("  Tag '%s' is currently missing.\n", targetKey)
					}
				} else {
					log.Warn().Str("kind", resource.Kind).Str("name", resource.Name).Str("issue", issue.IssueType).Msg("Could not parse any recommendation to determine target key for showing current value.")
				}

				fmt.Println("  Multiple recommendations found:")

				type recChoice struct {
					model string
					rec   string
				}
				choices := make([]recChoice, 0, len(issue.Recommendation))
				i := 1
				for model, rec := range issue.Recommendation {
					choices = append(choices, recChoice{model: model, rec: rec})
					fmt.Printf("    %d. [%s]: %s\n", i, model, rec)
					i++
				}

				fmt.Printf("Enter the number of the recommendation to apply (1-%d), 'e' to edit the chosen value, or anything else to skip: ", len(choices))
				inputText, _ := reader.ReadString('\n')
				inputText = strings.TrimSpace(strings.ToLower(inputText))

				applyChange := false
				editChoice := false
				var selectedChoice recChoice
				var action, key, value, editedValue string

				choiceIndex, err := strconv.Atoi(inputText)
				if err == nil && choiceIndex >= 1 && choiceIndex <= len(choices) {
					selectedChoice = choices[choiceIndex-1]
					log.Info().Str("kind", resource.Kind).Str("name", resource.Name).Int("choice", choiceIndex).Str("model", selectedChoice.model).Str("rec", selectedChoice.rec).Msg("User selected recommendation")
					fmt.Printf("Apply recommendation %d ([%s]: %s)? (y/N/e[dit]): ", choiceIndex, selectedChoice.model, selectedChoice.rec)
					confirmText, _ := reader.ReadString('\n')
					confirmText = strings.TrimSpace(strings.ToLower(confirmText))

					if confirmText == "y" {
						applyChange = true
					} else if confirmText == "e" {
						applyChange = true
						editChoice = true
					} else {
						log.Warn().Str("input", confirmText).Str("kind", resource.Kind).Str("name", resource.Name).Msg("User skipped applying chosen change")
						skippedCount++
					}

				} else if inputText == "e" {
					fmt.Printf("Which recommendation number (1-%d) do you want to edit and apply?: ", len(choices))
					editChoiceText, _ := reader.ReadString('\n')
					editChoiceText = strings.TrimSpace(editChoiceText)
					editIndex, editErr := strconv.Atoi(editChoiceText)
					if editErr == nil && editIndex >= 1 && editIndex <= len(choices) {
						selectedChoice = choices[editIndex-1]
						log.Info().Str("kind", resource.Kind).Str("name", resource.Name).Int("choice", editIndex).Str("model", selectedChoice.model).Str("rec", selectedChoice.rec).Msg("User selected recommendation to edit")
						applyChange = true
						editChoice = true
					} else {
						log.Warn().Str("input", editChoiceText).Str("kind", resource.Kind).Str("name", resource.Name).Msg("Invalid choice for editing, skipping")
						skippedCount++
					}
				} else {
					log.Warn().Str("input", inputText).Str("kind", resource.Kind).Str("name", resource.Name).Msg("User skipped applying change (invalid initial choice or non-numeric/non-'e' input)")
					skippedCount++
				}

				if applyChange {
					var parseErr error
					action, key, value, parseErr = recommendation.ParseRecommendation(selectedChoice.rec)
					if parseErr != nil {
						log.Error().Err(parseErr).Str("recommendation", selectedChoice.rec).Msg("Failed to parse selected recommendation, skipping")
						errorCount++
					} else {
						editedValue = value
						if editChoice {
							fmt.Printf("Original suggested value for tag '%s': '%s'\n", key, value)
							fmt.Printf("Enter new value for tag '%s': ", key)
							newValueText, _ := reader.ReadString('\n')
							editedValue = strings.TrimSpace(newValueText)
							log.Info().Str("action", action).Str("key", key).Str("originalValue", value).Str("newValue", editedValue).Str("kind", resource.Kind).Str("name", resource.Name).Msg("Applying edited change")
						} else {
							log.Info().Str("action", action).Str("key", key).Str("value", value).Str("kind", resource.Kind).Str("name", resource.Name).Msg("Applying selected change")
						}

						applyErr := applyTagChange(cfg, resource, action, key, editedValue)
						if applyErr != nil {
							log.Error().Err(applyErr).Msg("Failed to apply tag change")
							errorCount++
						} else {
							log.Info().Msg("Successfully applied tag change")
							appliedCount++
						}
					}
				}
				fmt.Println("---")
			}
		}
	}

	log.Info().
		Int("applied", appliedCount).
		Int("skipped", skippedCount).
		Int("errors", errorCount).
		Msg("Apply command finished.")
}

// applyTagChange dispatches the tag application to the correct AWS service function.
func applyTagChange(cfg *config.Config, resource ResourceInfo, action, key, value string) error {
	log.Debug().Str("kind", resource.Kind).Str("name", resource.Name).Str("region", resource.Region).Msg("Attempting to apply tag")

	client, err := aws.NewAWSClient(resource.Region)
	if err != nil {
		return fmt.Errorf("failed to create AWS client for region %s: %w", resource.Region, err)
	}

	tagsToApply := map[string]string{key: value}

	switch resource.Kind {
	case "ec2", "ebs", "vpc", "natgateway", "internetgateway", "eip":
		return client.ApplyTagsToEC2Resource(resource.Name, tagsToApply)
	case "elbv2":
		return client.ApplyTagsToELBv2Resource(resource.Name, tagsToApply)
	case "ecscluster":
		return client.ApplyTagsToECSResource(resource.Name, tagsToApply)
	case "s3":
		return client.ApplyTagsToS3Bucket(resource.Name, resource.Region, tagsToApply)
	default:
		return fmt.Errorf("unsupported resource kind for applying tags: %s", resource.Kind)
	}
}

// runVersionCommand prints the application version.
func runVersionCommand() {
	fmt.Printf("aws-tag-analyzer version %s\n", version)
}
